Repository OpenMined/syft.js, pull requests merged in 2020-08, with the labels that each got.

#199 Documentation: src/syft-model.js
  src/protobuf/mapping.js
  src/syft-model.js
Labels: Type: Documentation :books:

#201 Documentation: src/sockets
  src/sockets.js
Labels: Type: Documentation :books:

#211 Avoid Buffer and crypto dependencies
  .babelrc
  README.md
  package-lock.json
  package.json
  rollup.config.js
  src/job.js
  src/protobuf/index.js
  src/speed-test.js
  src/utils/base64.js
  src/utils/random-buffer.js
Labels: Severity: 1 - Critical :fire:, Status: Review Needed :raising_hand:, Type: Bug :bug:, Type: Improvement :chart_with_upwards_trend:

#207 Documentation: src/types/message.js
  src/types/message.js
Labels: Type: Documentation :books:

#208 Documentation - src/types/placeholder.js
  src/types/placeholder.js
  test/types/placeholder.test.js
Labels: Type: Documentation :books:

#209 Test - src/sockets.js
  test/sockets.test.js
Labels: Type: Documentation :books:, Type: Testing :test_tube:

#215 Documentation - ComputationAction
  src/object-registry.js
  src/types/computation-action.js
  src/types/placeholder.js
Labels: Type: Documentation :books:

#216 Change to per-job authentication
  API-REFERENCE.md
  examples/mnist/index.js
  examples/multi-armed-bandit/index.js
  src/_constants.js
  src/_errors.js
  src/data-channel-message.js
  src/grid-api-client.js
  src/job.js
  src/syft-webrtc.js
  src/syft.js
  src/types/protocol.js
  src/types/role.js
  src/types/state.js
  src/types/torch.js
  src/webrtc.js
  test/syft.test.js
Labels: Status: Review Needed :raising_hand:, Type: Improvement :chart_with_upwards_trend:, Type: Refactor :hammer:

#217 Add prettier in CI checks
  .github/workflows/run-tests.yml
  .prettierignore
Labels: Severity: 4 - Low :sunglasses:, Status: Review Needed :raising_hand:

#218 Documentation - src/types/role.js
  src/types/role.js
Labels: Type: Documentation :books:
