Repository OpenMined/syft.js, pull requests merged in 2020-07, with the labels that each got.

#174 Migrate to TFJS-traslated plans
  examples/mnist/index.html
  examples/mnist/index.js
  package-lock.json
  package.json
  src/_errors.js
  src/grid-api-client.js
  src/syft.js
  src/types/computation-action.js
  test/data/dummy.js
  test/data/generate-data.py
  test/types/plan.test.js
Labels: Status: Review Needed :raising_hand:, Type: Improvement :chart_with_upwards_trend:, Type: Refactor :hammer:

#175 Update readme to reference pysyft, pygrid installation docs
  README.md
Labels: Status: Review Needed :raising_hand:, Type: Documentation :books:

#176 Add tests with bandit plans
  test/data/dummy.js
  test/data/dummy.tpl.js
  test/data/generate-data.py
  test/types/plan.test.js
Labels: Type: Research :microscope:, Type: Testing :test_tube:

#193 Make pygrid speed test optional
  API-REFERENCE.md
  src/job.js
  src/syft.js
  test/syft.test.js
Labels: Type: Improvement :chart_with_upwards_trend:

#192 Fix speed test edge case
  src/speed-test.js
Labels: Type: Bug :bug:

#195 Documentation: Edit src/syft.js
  API-REFERENCE.md
  src/syft.js
Labels: Type: Documentation :books:

#197 Documentation: src/job.js
  API-REFERENCE.md
  src/events.js
  src/job.js
  src/syft.js
Labels: Type: Documentation :books:
