Repository OpenMined/syft.js, pull requests merged in 2020-09, with the labels that each got.

#224 Documentation: src/types/plan.js
  API-REFERENCE.md
  src/types/computation-action.js
  src/types/placeholder.js
  src/types/plan.js
  src/types/role.js
Labels: Type: Documentation :books:

#226 Add training API
  API-REFERENCE.md
  README.md
  documentation.yml
  examples/mnist/index.js
  examples/multi-armed-bandit/index.js
  package.json
  src/index.js
  src/job.js
  src/plan-trainer.js
  src/syft-model.js
  src/syft.js
  src/types/plan.js
  test/data-channel-message-queue.test.js
  test/data-channel-message.test.js
  test/plan-trainer.test.js
  test/syft.test.js
Labels: Status: Review Needed :raising_hand:, Type: New Feature :heavy_plus_sign:

#228 Add stop/resume methods and checkpoint object
  API-REFERENCE.md
  README.md
  documentation.yml
  examples/mnist/checkpoint.js
  examples/mnist/index.html
  examples/mnist/index.js
  src/events.js
  src/index.js
  src/job.js
  src/plan-trainer.js
  src/syft-model.js
  src/types/torch.js
  test/plan-trainer.test.js
Labels: Status: Review Needed :raising_hand:

#229 Handle WS responses by request_id
  API-REFERENCE.md
  src/grid-api-client.js
  test/mocks/grid.js
Labels: Status: Review Needed :raising_hand:, Type: Improvement :chart_with_upwards_trend:

#230 Documentation - PointerTensor
  src/types/pointer-tensor.js
Labels: Type: Documentation :books:

#231 Documentation: Protocol
  src/types/protocol.js
Labels: Type: Documentation :books:
